package taigo

//TODO refine tests to reach 100% code coverage
//github.com/reusee/tai/taigo/builtins.go:10:	registerBuiltins	80.0%
//github.com/reusee/tai/taigo/compile.go:9:	compile			100.0%
//github.com/reusee/tai/taigo/compiler.go:29:	getFunction		100.0%
//github.com/reusee/tai/taigo/compiler.go:37:	emit			100.0%
//github.com/reusee/tai/taigo/compiler.go:41:	emitJump		100.0%
//github.com/reusee/tai/taigo/compiler.go:47:	patchJump		100.0%
//github.com/reusee/tai/taigo/compiler.go:58:	enterLoop		100.0%
//github.com/reusee/tai/taigo/compiler.go:67:	leaveLoop		91.7%
//github.com/reusee/tai/taigo/compiler.go:88:	addConst		100.0%
//github.com/reusee/tai/taigo/compiler.go:98:	loadConst		100.0%
//github.com/reusee/tai/taigo/compiler.go:103:	compileFile		95.0%
//github.com/reusee/tai/taigo/compiler.go:139:	compileDecl		50.0%
//github.com/reusee/tai/taigo/compiler.go:161:	compileFuncDecl		100.0%
//github.com/reusee/tai/taigo/compiler.go:176:	compileInitFunc		87.5%
//github.com/reusee/tai/taigo/compiler.go:190:	compileFunc		94.1%
//github.com/reusee/tai/taigo/compiler.go:224:	compileExpr		56.5%
//github.com/reusee/tai/taigo/compiler.go:289:	emitBinaryOp		88.9%
//github.com/reusee/tai/taigo/compiler.go:303:	tokenToOp		84.2%
//github.com/reusee/tai/taigo/compiler.go:343:	compileBasicLiteral	72.7%
//github.com/reusee/tai/taigo/compiler.go:385:	compileIdentifier	100.0%
//github.com/reusee/tai/taigo/compiler.go:400:	compileBinaryExpr	88.9%
//github.com/reusee/tai/taigo/compiler.go:418:	compileLogicAnd		77.8%
//github.com/reusee/tai/taigo/compiler.go:438:	compileLogicOr		81.8%
//github.com/reusee/tai/taigo/compiler.go:463:	compileUnaryExpr	66.7%
//github.com/reusee/tai/taigo/compiler.go:502:	compileCallExpr		73.7%
//github.com/reusee/tai/taigo/compiler.go:543:	compileIndexExpr	66.7%
//github.com/reusee/tai/taigo/compiler.go:554:	compileSelectorExpr	80.0%
//github.com/reusee/tai/taigo/compiler.go:563:	compileSliceExpr	76.9%
//github.com/reusee/tai/taigo/compiler.go:591:	compileFuncLit		84.2%
//github.com/reusee/tai/taigo/compiler.go:627:	compileCompositeLit	76.5%
//github.com/reusee/tai/taigo/compiler.go:665:	compileStmt		81.0%
//github.com/reusee/tai/taigo/compiler.go:730:	compileExprStmt		75.0%
//github.com/reusee/tai/taigo/compiler.go:738:	compileBlockStmt	87.5%
//github.com/reusee/tai/taigo/compiler.go:751:	compileReturnStmt	69.2%
//github.com/reusee/tai/taigo/compiler.go:775:	compileAssignStmt	100.0%
//github.com/reusee/tai/taigo/compiler.go:791:	compileMultiAssign	52.0%
//github.com/reusee/tai/taigo/compiler.go:840:	compileSingleAssign	76.9%
//github.com/reusee/tai/taigo/compiler.go:887:	compileCompoundAssign	75.7%
//github.com/reusee/tai/taigo/compiler.go:954:	compileIncDecStmt	100.0%
//github.com/reusee/tai/taigo/compiler.go:973:	compileDeclStmt		100.0%
//github.com/reusee/tai/taigo/compiler.go:981:	compileIfStmt		52.4%
//github.com/reusee/tai/taigo/compiler.go:1019:	compileSwitchStmt	86.5%
//github.com/reusee/tai/taigo/compiler.go:1111:	compileForStmt		82.6%
//github.com/reusee/tai/taigo/compiler.go:1152:	compileRangeStmt	79.2%
//github.com/reusee/tai/taigo/compiler.go:1199:	compileBranchStmt	84.6%
//github.com/reusee/tai/taigo/compiler.go:1223:	compileAssignLHS	66.7%
//github.com/reusee/tai/taigo/compiler.go:1240:	compileGenDecl		92.0%
//github.com/reusee/tai/taigo/compiler.go:1290:	typeToString		0.0%
//github.com/reusee/tai/taigo/vm.go:11:		NewVM			90.0%
//total:						(statements)		77.6%
